import { Link } from "react-router";
import { ARTWORK, type ArtEntry, SECTION_ART, artSourceUrl } from "../art/manifest";
import { Artwork } from "../components/Artwork";
import { useBackdrop } from "../components/Backdrop";

const FONTS = [
  {
    name: "Bodoni Moda",
    by: "Owen Earl (indestructible type*)",
    licence: "SIL Open Font License 1.1",
  },
  { name: "Barlow Condensed", by: "Jeremy Tribby", licence: "SIL Open Font License 1.1" },
  {
    name: "Final Fantasy (logo lettering)",
    by: "Juan Pablo Reyes Altamirano, after the series' logo",
    licence: "Free font (1999), non-commercial use",
  },
  { name: "Optimus Princeps", by: "Manfred Klein", licence: "Free font" },
  {
    name: "Reactor7",
    by: "Caveras (Cliff Modes), after the original game's text font",
    licence: "CC BY-NC-SA 4.0 — caveras.net",
  },
  { name: "Inter", by: "Rasmus Andersson", licence: "SIL Open Font License 1.1" },
  { name: "JetBrains Mono", by: "JetBrains", licence: "SIL Open Font License 1.1" },
] as const;

const GROUPS: readonly { id: string; name: string; match: (art: ArtEntry) => boolean }[] = [
  { id: "key", name: "Key art and illustrations", match: (art) => art.id.startsWith("key/") },
  { id: "characters", name: "Characters", match: (art) => art.id.startsWith("characters/") },
  { id: "places", name: "Places", match: (art) => art.id.startsWith("places/") },
];

/** Who made what: official artwork, fonts, and the licences of this project's own work. */
export function CreditsPage() {
  useBackdrop(SECTION_ART.credits, { strength: 0.45 });

  return (
    <div className="flex flex-col gap-10">
      <header className="flex max-w-4xl flex-col gap-2">
        <p className="eyebrow">Acknowledgements</p>
        <h1 className="page-title">Credits</h1>
        <p className="text-steel-300">
          <em>Final Fantasy VII</em> and all related names, characters and artwork belong to Square
          Enix. This is a non-commercial fan project, not affiliated with or endorsed by Square
          Enix.
        </p>
      </header>

      <section aria-labelledby="credits-art" className="flex flex-col gap-4">
        <h2 id="credits-art" className="section-title">
          Official artwork
        </h2>
        <p className="max-w-4xl text-sm text-steel-300">
          Every image is official Square Enix artwork — key art, character renders and
          illustrations, and concept art — found through the{" "}
          <a
            href="https://finalfantasy.fandom.com"
            target="_blank"
            rel="noreferrer"
            className="text-steel-100 underline underline-offset-2 hover:text-mako-300"
          >
            Final Fantasy Wiki
            <span className="sr-only"> (opens in a new tab)</span>
          </a>
          . Artwork is decoration only, never a source of facts. None of it is extracted from the
          games or generated by AI. Images are resized; flat studio backgrounds around some figures
          are removed; pencil concept sketches are shown as light lines on the dark page; and
          printed titles and publisher logos are cropped off. Nothing is covered by this
          project&apos;s licences, and any image will be removed at the rights holder&apos;s
          request.
        </p>
        {GROUPS.map((group) => (
          <section
            key={group.id}
            aria-labelledby={`credits-${group.id}`}
            className="flex flex-col gap-3"
          >
            <h3 id={`credits-${group.id}`} className="label">
              {group.name}{" "}
              <span className="text-steel-300">{ARTWORK.filter(group.match).length}</span>
            </h3>
            <ul className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">
              {ARTWORK.filter(group.match).map((art) => (
                <li key={art.id} className="panel flex gap-3 p-2.5">
                  <span className="halftone flex h-20 w-24 shrink-0 items-center justify-center overflow-hidden bg-night-950">
                    <Artwork
                      entry={art}
                      decorative
                      className={`max-h-full ${art.kind === "cutout" ? "object-contain" : "h-full w-full object-cover"}`}
                    />
                  </span>
                  <div className="flex min-w-0 flex-col gap-0.5 text-sm">
                    <p className="font-semibold text-steel-100">{art.title}</p>
                    <p className="text-xs text-steel-400">{art.artist} · © Square Enix</p>
                    {art.wiki === undefined ? (
                      <p className="text-xs text-steel-300">{art.source}</p>
                    ) : (
                      <a
                        href={artSourceUrl(art)}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-block min-h-6 truncate py-0.5 text-xs text-steel-200 underline underline-offset-2 hover:text-mako-300"
                      >
                        Source
                        <span className="sr-only">
                          {" "}
                          for {art.title} on the Final Fantasy Wiki (opens in a new tab)
                        </span>
                      </a>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </section>

      <section aria-labelledby="credits-fonts" className="flex max-w-4xl flex-col gap-3">
        <h2 id="credits-fonts" className="section-title">
          Typefaces
        </h2>
        <ul className="panel divide-y divide-night-800 text-sm">
          {FONTS.map((font) => (
            <li key={font.name} className="flex flex-wrap justify-between gap-2 p-3">
              <span className="text-steel-100">
                {font.name} <span className="text-steel-400">by {font.by}</span>
              </span>
              <span className="text-steel-400">{font.licence}</span>
            </li>
          ))}
        </ul>
      </section>

      <section aria-labelledby="credits-pieces" className="flex max-w-4xl flex-col gap-3">
        <h2 id="credits-pieces" className="section-title">
          Icon and cursor
        </h2>
        <ul className="panel divide-y divide-night-800 text-sm">
          <li className="flex flex-wrap justify-between gap-2 p-3">
            <span className="text-steel-100">
              Site icon{" "}
              <span className="text-steel-400">
                the Meteor emblem from the series&apos; logo, by Yoshitaka Amano
              </span>
            </span>
            <span className="text-steel-400">© Square Enix</span>
          </li>
          <li className="flex flex-wrap justify-between gap-2 p-3">
            <span className="text-steel-100">
              Cursor{" "}
              <span className="text-steel-400">
                &ldquo;Final Fantasy 7 – Cloud&apos;s Buster Sword&rdquo; from{" "}
                <a
                  href="https://www.cursors-4u.com/cursor/final-fantasy-7-cloud-s-buster-sword"
                  className="underline underline-offset-2 hover:text-mako-300"
                >
                  Cursors-4U
                </a>
              </span>
            </span>
            <span className="text-steel-400">Free cursor, credited as Cursors-4U asks</span>
          </li>
        </ul>
      </section>

      <section aria-labelledby="credits-project" className="flex max-w-4xl flex-col gap-3">
        <h2 id="credits-project" className="section-title">
          This project
        </h2>
        <ul className="flex flex-col gap-1.5 text-sm text-steel-300">
          <li>
            <span className="text-steel-100">Code</span>: MIT licence.
          </li>
          <li>
            <span className="text-steel-100">Data and documentation</span>: Creative Commons
            Attribution-NonCommercial 4.0 (reuse with attribution, non-commercial only).
          </li>
          <li>
            <span className="text-steel-100">Research</span>: the sources used to check each fact
            are listed in the{" "}
            <Link
              to="/archive/research"
              className="text-steel-200 underline underline-offset-2 hover:text-mako-300"
            >
              research log
            </Link>
            .
          </li>
        </ul>
      </section>
    </div>
  );
}
